name: deploy experience to dev
on:
  push:
    tags:
      - deploy/experience/dev/v*.*.*
jobs:
  doEcho:
    runs-on: ubuntu-latest
    steps:
      - name: do echo
        run: echo "deploy/experience/dev"
