name: deploy experience to dev
on:
  push:
    tags:
      - deploy/experience/prod/v*.*.*
jobs:
  echo-example:
    runs-on: ubuntu-latest
    steps:
      - name: do echo
        run: echo "deploy/experience/prod"
