name: deploy experience to prod
on:
  push:
    tags:
      - deploy/experience/prod/v*.*.*
jobs:
  doEcho:
    runs-on: ubuntu-latest
    steps:
      - name: do echo
        run: echo "deploy/experience/prod"
